import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,validateState,status,daysLeft,validDate,consume,purchase} from '../site/static/app/core.mjs';
const item=()=>({id:'a',name:'牛奶',quantity:2,unit:'瓶',location:'冷藏',expiry:'2026-09-12'});
const state=()=>({...emptyState(),items:[item()]});
test('date boundaries are calendar-day based, including leap dates',()=>{assert.equal(validDate('2026-02-29'),false);assert.equal(validDate('2024-02-29'),true);assert.equal(status('2026-09-09','2026-09-09').label,'今天到期');assert.equal(status('2026-09-08','2026-09-09').key,'expired');assert.equal(status('2026-09-12','2026-09-09').key,'soon');assert.equal(status('2026-09-13','2026-09-09').key,'fresh');assert.equal(daysLeft('2026-11-02','2026-11-01'),1);});
test('partial consumption is exact and records confirmed quantity',()=>{let s=state();s.items[0].quantity=.3;consume(s,'a',.1,'consume','h','2026-09-09T00:00:00Z');assert.equal(s.items[0].quantity,.2);assert.equal(s.history[0].quantity,.1);validateState(s);consume(s,'a',.2,'waste','h2','2026-09-09T00:00:00Z');assert.equal(s.items.length,0);assert.equal(s.history.length,2);});
test('overconsumption, negative and missing records cannot mutate state',()=>{for(const n of [-1,0,2.1,NaN,Infinity]){const s=state();assert.throws(()=>consume(s,'a',n,'consume','h','2026-09-09'));assert.deepEqual(s,state());}assert.throws(()=>consume(state(),'gone',1,'consume','h','2026-09-09'));});
test('purchase moves exactly one list item into inventory',()=>{const s=emptyState();s.shopping=[{id:'q',name:'牛奶',quantity:2,unit:'瓶'}];const next=purchase(s,'q',item());assert.equal(next.shopping.length,0);assert.equal(next.items.length,1);assert.throws(()=>purchase(next,'q',item()));});
test('backup rejects unsupported versions, duplicates, invalid dates, quantities, enums and missing fields',()=>{for(const mutate of [s=>s.version=2,s=>s.items.push(item()),s=>s.items[0].quantity=-1,s=>s.items[0].expiry='2026-02-30',s=>s.items[0].unit='invalid',s=>delete s.shopping,s=>s.revision=-1]){const s=state();mutate(s);assert.throws(()=>validateState(s));}});
test('backup roundtrip preserves data and strips unexpected fields',()=>{const s=state();s.items[0].unexpected='script';s.unexpected='x';const restored=validateState(JSON.parse(JSON.stringify(s)));assert.deepEqual(restored,state());});

import {matchingHistory,shoppingText} from '../site/static/app/core.mjs';
test('history combines name and type filters and sorts without mutating records',()=>{const rows=[{name:'牛奶',kind:'consume',at:'2026-09-08T01:00:00Z'},{name:'牛奶',kind:'waste',at:'2026-09-09T01:00:00Z'},{name:'鸡蛋',kind:'consume',at:'2026-09-09T02:00:00Z'}];assert.deepEqual(matchingHistory(rows,' 牛奶 ','consume'),[rows[0]]);assert.equal(matchingHistory(rows)[0],rows[2]);assert.equal(rows[0].at,'2026-09-08T01:00:00Z');assert.deepEqual(matchingHistory(rows,'不存在'),[]);});
test('shopping text keeps units and decimal quantities',()=>{assert.equal(shoppingText([{name:'牛奶',quantity:1.5,unit:'升'},{name:'鸡蛋',quantity:6,unit:'个'}]),'FreshLife 购物清单\n□ 牛奶 · 1.5 升\n□ 鸡蛋 · 6 个');});
import {sortedInventory,matchingShopping} from '../site/static/app/core.mjs';
test('inventory sort keeps input intact and groups storage locations',()=>{const a={...item(),id:'a',name:'Z',location:'常温',expiry:'2026-10-01'},b={...item(),id:'b',name:'A',location:'冷藏',expiry:'2026-10-03'};const rows=[a,b];assert.deepEqual(sortedInventory(rows,'expiry'),[a,b]);assert.deepEqual(sortedInventory(rows,'location'),[b,a]);assert.deepEqual(sortedInventory(rows,'name'),[b,a]);assert.deepEqual(rows,[a,b]);});
test('shopping search is trimmed, case insensitive and non-destructive',()=>{const rows=[{name:'Milk'},{name:'鸡蛋'}];assert.deepEqual(matchingShopping(rows,' MILK '),[rows[0]]);assert.deepEqual(matchingShopping(rows,' '),rows);assert.deepEqual(matchingShopping(rows,'不存在'),[]);});
import {MAX_BACKUP_BYTES,restoreBackup} from '../site/static/app/core.mjs';
test('maximum supported records fit the backup import limit',()=>{const s=emptyState(),name='鲜'.repeat(80);s.items=Array.from({length:2500},(_,i)=>({...item(),id:String(i),name}));s.shopping=s.items.map(({id,name,quantity,unit})=>({id,name,quantity,unit}));s.history=Array.from({length:10000},(_,i)=>({id:'史'.repeat(90)+i,name,quantity:1000000,unit:'千克',kind:'consume',at:'2026-09-09T00:00:00Z'}));const bytes=Buffer.byteLength(JSON.stringify(validateState(s)));assert.ok(bytes>5*1024*1024,'regression fixture exceeds the previous limit');assert.ok(bytes<MAX_BACKUP_BYTES);});
test('restore preserves local revision and rejects changes after preview without mutation',()=>{const current={...state(),revision:7};const backup={...emptyState(),revision:999};const restored=restoreBackup(current,backup,7);assert.equal(restored.revision,7);assert.equal(restored.items.length,0);assert.equal(current.items.length,1);assert.equal(backup.revision,999);assert.throws(()=>restoreBackup(current,backup,6));assert.equal(current.revision,7);});
test('partial purchase keeps unbought quantities on the list',()=>{const s=emptyState();s.shopping=[{id:'q',name:'牛奶',quantity:3,unit:'瓶'}];const next=purchase(s,'q',{...item(),quantity:1});assert.equal(next.items[0].quantity,1);assert.equal(next.shopping[0]?.quantity,2);assert.equal(s.shopping[0].quantity,3);});
test('purchase with mismatched units is rejected without changing either list',()=>{const s=emptyState();s.shopping=[{id:'q',name:'牛奶',quantity:3,unit:'瓶'}];assert.throws(()=>purchase(s,'q',{...item(),unit:'升'}));assert.equal(s.items.length,0);assert.equal(s.shopping[0].quantity,3);});

test('extra purchase and decimal remainder are handled without negative balances',()=>{const s=emptyState();s.shopping=[{id:'q',name:'牛奶',quantity:.3,unit:'瓶'}];const partial=purchase(s,'q',{...item(),quantity:.1});assert.equal(partial.shopping[0].quantity,.2);const extra=purchase(partial,'q',{...item(),id:'b',quantity:.5});assert.equal(extra.shopping.length,0);assert.equal(extra.items[1].quantity,.5);});
