import {emptyState,validateState,status,today,consume,purchase,MAX_ITEMS,matchingHistory,shoppingText,sortedInventory,matchingShopping,MAX_BACKUP_BYTES,restoreBackup} from './core.mjs';
const $=s=>document.querySelector(s);
let state=emptyState(),db,view='pantry',editing=null,pending=null,busy=false,channel;
const uid=()=>crypto.randomUUID();
const message=e=>e instanceof Error?e.message:'操作失败，请重试。';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let toastTimer, lastUndo, historyLimit=100, formBaseline="";
const formSnapshot=()=>JSON.stringify([...new FormData($("#item-form")).entries()]);
const hasDraft=()=>$("#editor").open&&formSnapshot()!==formBaseline;
function toast(text, undo=false){$('#toast').textContent=text;$('#toast').hidden=false;if(undo&&lastUndo){const saved=lastUndo;const button=document.createElement('button');button.textContent='撤销';button.onclick=async()=>{if(!saved)return;try{await update(s=>{if(s.revision!==saved.revision)throw new Error('记录已有新变化，无法撤销；请在库存中调整。');return saved.state;});toast('已撤销，库存和记录已恢复');}catch(e){toast(message(e));}};$('#toast').append(button);}clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,undo?12000:5000);}
function fatal(text){$('#fatal').textContent=text;$('#fatal').hidden=false;}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('freshlife-web',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('浏览器无法打开本地存储。请检查隐私设置，或换用允许网站保存数据的普通浏览窗口。'));r.onblocked=()=>reject(new Error('存储更新被其他窗口占用，请关闭其他 FreshLife 网页后重试。'));});}
function read(){return new Promise((resolve,reject)=>{const tx=db.transaction('records','readonly');const r=tx.objectStore('records').get('state');r.onsuccess=()=>{try{resolve(validateState(r.result??emptyState()));}catch(e){reject(e);}};r.onerror=()=>reject(r.error);});}
function update(change, undoable=false){return new Promise((resolve,reject)=>{if(!db){reject(new Error('本地存储未就绪，尚未保存。'));return;}const tx=db.transaction('records','readwrite');const store=tx.objectStore('records');const r=store.get('state');let next,reason,before;r.onsuccess=()=>{try{const current=validateState(r.result??emptyState());before=structuredClone(current);next=validateState(change(current)??current);next.revision=current.revision+1;if(!Number.isSafeInteger(next.revision))throw new Error('本地记录版本异常，请先导出备份。');store.put(next,'state');}catch(e){reason=e;tx.abort();}};tx.oncomplete=()=>{lastUndo=undoable?{state:before,revision:next.revision}:null;state=next;render();channel?.postMessage('changed');resolve();};tx.onabort=()=>reject(reason??new Error('无法保存到浏览器，可能存储空间不足。当前操作没有生效，请导出备份并检查浏览器设置。'));tx.onerror=()=>{};});}
function setView(v){if(!['pantry','shopping','history','data'].includes(v))v='pantry';view=v;for(const key of ['pantry','shopping','history','data'])$(`#${key}-view`).hidden=key!==v;document.querySelectorAll('nav [data-view]').forEach(b=>{if(b.dataset.view===v)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const words={pantry:['我的库存','先看该用的，再安排今天。','＋ 添加食材'],shopping:['购物清单','买之前看一眼，缺什么才买什么。','＋ 记下要买的'],history:['使用记录','每一次确认，都让库存更准确。',''],data:['数据与备份','把记录保存在自己手里。','']};$('#page-title').textContent=words[v][0];$('#page-description').textContent=words[v][1];$('#add').textContent=words[v][2];$('#add').hidden=!words[v][2];history.replaceState(null,'','#'+v);render();}
function empty(title,description,label,action){return `<div class="empty"><div class="empty-mark" aria-hidden="true">＋</div><h2>${title}</h2><p>${description}</p>${label?`<button class="primary" data-action="${action}">${label}</button>`:''}</div>`;}
const actionButton=(action,id,label)=>`<button data-action="${action}" data-id="${escape(id)}">${label}</button>`;
function render(){
 document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===$('#filter').value)));
 $('#count-all').textContent=state.items.length;$('#count-soon').textContent=state.items.filter(x=>status(x.expiry).key==='soon').length;$('#count-expired').textContent=state.items.filter(x=>status(x.expiry).key==='expired').length;
 const query=$('#search').value.trim().toLocaleLowerCase(),filter=$('#filter').value,loc=$('#location-filter').value;
 const items=sortedInventory(state.items.filter(x=>(!query||x.name.toLocaleLowerCase().includes(query))&&(filter==='all'||status(x.expiry).key===filter)&&(loc==='all'||x.location===loc)),$('#inventory-order').value);
 $('#result-note').textContent=`显示 ${items.length} / ${state.items.length} 件 · ${{expiry:'最早到期优先',name:'按名称排列',location:'按储存位置排列'}[$('#inventory-order').value]}`;
 $('#inventory').innerHTML=items.map(x=>{const st=status(x.expiry);return `<article class="item"><div class="food-icon" aria-hidden="true">${escape([...x.name][0])}</div><div class="item-body"><h3>${escape(x.name)}</h3><p>${x.quantity} ${escape(x.unit)} · ${escape(x.location)} · ${x.expiry} 到期</p></div><span class="badge ${st.key}">${st.label}</span><div class="item-actions">${actionButton('consume',x.id,'用掉')}${actionButton('waste',x.id,'丢弃')}${actionButton('restock',x.id,'加入采购')}${actionButton('edit',x.id,'编辑')}${actionButton('delete',x.id,'移除')}</div></article>`;}).join('') || (state.items.length?empty('没有找到对应食材','换个名称，或清除筛选看看。','清除筛选','reset-filter'):empty('从冰箱里的一件食材开始','记下名称、数量和到期日期。下次打开，就知道家里有什么、哪些该先用。','添加第一件食材','add'));
 const shopping=matchingShopping(state.shopping,$('#shopping-search').value);
 $('#shopping-list').innerHTML=shopping.map(x=>`<article class="item"><div class="food-icon" aria-hidden="true">${escape([...x.name][0])}</div><div class="item-body"><h3>${escape(x.name)}</h3><p>计划购买 ${x.quantity} ${escape(x.unit)}</p></div><div class="item-actions">${actionButton('purchase',x.id,'买到了，入库')}${actionButton('edit-shop',x.id,'编辑')}${actionButton('delete-shop',x.id,'移除')}</div></article>`).join('')||(state.shopping.length?empty('没有匹配的采购项','换个名称搜索，或清空搜索框查看全部清单。','',''):empty('需要补充什么？','先记进清单。买到后补上到期日期，一次确认就能加入库存。','记下要买的','add'));
 const records=matchingHistory(state.history,$('#history-search').value,$('#history-kind').value);
 $('#shopping-count').textContent=`${shopping.length} / ${state.shopping.length} 项待采购`;$('#copy-shopping').disabled=!state.shopping.length;
 $('#history-count').textContent=`显示 ${Math.min(historyLimit,records.length)} / ${records.length} 条匹配记录`;$('#history-more').hidden=records.length<=historyLimit;
 $('#history-list').innerHTML=records.slice(0,historyLimit).map(x=>`<article class="item"><div class="food-icon" aria-hidden="true">${x.kind==='consume'?'✓':'−'}</div><div class="item-body"><h3>${escape(x.name)}</h3><p>${escape(new Date(x.at).toLocaleString('zh-CN'))}</p></div><span class="badge ${x.kind==='waste'?'expired':''}">${{consume:'用掉',waste:'丢弃',delete:'移除'}[x.kind]} ${x.quantity} ${escape(x.unit)}</span></article>`).join('')||(state.history.length?empty('没有匹配的记录','试试其他食材名称，或切换记录类型。','',''):empty('还没有使用记录','在库存中确认「用掉」或「丢弃」，这里会留下记录，同时扣减库存。','',''));
}
function edit(mode,id,source){if(!db)return toast('本地存储未就绪，请先处理上方提示。');const x=source??(mode==='edit'?state.items:state.shopping).find(x=>x.id===id);if(id&&!x)return toast('记录已更新，请重新选择。');editing={mode,id,original:x?JSON.stringify(x):null};const form=$('#item-form');form.reset();const isShop=['shop','edit-shop','restock'].includes(mode);$('#pantry-fields').hidden=isShop;form.elements.expiry.required=!isShop;form.elements.expiry.disabled=isShop;$('#editor-title').textContent=({add:'添加食材',edit:'编辑食材',shop:'记下要买的','edit-shop':'编辑购物清单',restock:'加入购物清单',purchase:'确认买到的食材'})[mode];$('#editor-note').textContent=isShop?'先记下需要的数量，买到后再确认入库。':'按包装填写到期日期，不自动猜测保质期。';if(x){for(const k of ['name','quantity','unit','location','expiry'])if(x[k]!==undefined)form.elements[k].value=x[k];}if(mode==='purchase')form.elements.expiry.value='';$('#editor-success').hidden=true;$('#save-next').hidden=!['add','shop'].includes(mode);$('#editor-error').textContent='';$('#discard-warning').hidden=true;formBaseline=formSnapshot();$('#editor').showModal();form.elements.name.focus();}
$('#item-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const f=e.currentTarget;const data={name:f.elements.name.value.trim(),quantity:Number(f.elements.quantity.value),unit:f.elements.unit.value};if(!data.name){$('#editor-error').textContent='请填写食材名称。';return;}const keepAdding=e.submitter?.value==='next'&&['add','shop'].includes(editing.mode);const mode=editing.mode,isShop=['shop','edit-shop','restock'].includes(mode);if(!isShop)Object.assign(data,{location:f.elements.location.value,expiry:f.elements.expiry.value});busy=true;const submitButtons=[...f.querySelectorAll('[type=submit]')];submitButtons.forEach(b=>b.disabled=true);try{await update(s=>{if(['edit','edit-shop','purchase'].includes(mode)){const list=mode==='edit'?s.items:s.shopping;const i=list.findIndex(x=>x.id===editing.id);if(i<0||JSON.stringify(list[i])!==editing.original)throw new Error('这条记录已在其他窗口更改，请关闭后重新编辑。');if(mode==='purchase')return purchase(s,editing.id,{id:uid(),...data});list[i]={id:editing.id,...data};}else{const list=isShop?s.shopping:s.items;if(list.length>=MAX_ITEMS)throw new Error('记录数量已满，请先整理。');list.push({id:uid(),...data});}return s;});if(keepAdding){$('#editor-success').textContent=`已保存「${data.name}」，可以继续添加下一件。`;$('#editor-success').hidden=false;f.elements.name.value='';f.elements.quantity.value='1';f.elements.expiry.value='';$('#editor-error').textContent='';$('#discard-warning').hidden=true;formBaseline=formSnapshot();f.elements.name.focus();}else $('#editor').close();toast(mode==='purchase'?'已加入库存，并从购物清单移除':'已保存到此浏览器');}catch(err){$('#editor-error').textContent=message(err);}finally{busy=false;submitButtons.forEach(b=>b.disabled=false);}});
function ask(title,description,run,quantity){pending=run;$('#action-title').textContent=title;$('#action-description').textContent=description;$('#amount-label').hidden=quantity===undefined;$('#amount').required=quantity!==undefined;$('#amount').disabled=quantity===undefined;$('#amount').value=quantity??'';$('#amount').max=quantity??1000000;$('#action-error').textContent='';$('#action-dialog').showModal();}
$('#action-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;$('#action-submit').disabled=true;try{await pending(Number($('#amount').value));$('#action-dialog').close();toast('已完成，并保存在此浏览器',Boolean(lastUndo));}catch(err){$('#action-error').textContent=message(err);}finally{busy=false;$('#action-submit').disabled=false;}});
function closeDialog(dialog){if(busy)return;if(dialog.id==='editor'&&hasDraft()){$('#discard-warning').hidden=false;$('#keep-editing').focus();return;}dialog.close();}
for(const dialog of document.querySelectorAll('dialog')){dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDialog(dialog));dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog(dialog);});}
$('#keep-editing').onclick=()=>{$('#discard-warning').hidden=true;$('#item-form').elements.name.focus();};
$('#discard-editing').onclick=()=>{if(!busy)$('#editor').close();};
window.addEventListener('beforeunload',e=>{if(hasDraft()||busy){e.preventDefault();e.returnValue='';}});
document.addEventListener('click',e=>{
 const tab=e.target.closest('[data-view]');if(tab){e.preventDefault();setView(tab.dataset.view);return;}
 const counter=e.target.closest('[data-filter]');if(counter){$('#filter').value=counter.dataset.filter;render();return;}
 const btn=e.target.closest('[data-action]');if(!btn)return;const {action,id}=btn.dataset;
 if(action==='add')return edit(view==='shopping'?'shop':'add');if(action==='reset-filter'){$('#search').value='';$('#filter').value='all';$('#location-filter').value='all';render();return;}
 if(['edit','edit-shop','purchase'].includes(action))return edit(action,id);
 const x=(action==='delete-shop'?state.shopping:state.items).find(x=>x.id===id);if(!x)return toast('这条记录已更新，请重新选择。');
 if(action==='restock')return edit('restock',undefined,x);
 if(['consume','waste'].includes(action))return ask(action==='consume'?'确认用掉多少？':'确认丢弃多少？',`${x.name} · 当前 ${x.quantity} ${x.unit}。确认后会扣减库存并记录。${action==='consume'&&status(x.expiry).key==='expired'?' 该食材已超过记录的到期日，请先检查食品状态。':''}`,n=>update(s=>{if(JSON.stringify(s.items.find(y=>y.id===id))!==JSON.stringify(x))throw new Error('库存已被其他窗口更改，请关闭后重新确认数量。');return consume(s,id,n,action,uid(),new Date().toISOString());},true),x.quantity);
 if(action==='delete'||action==='delete-shop')ask('移除这条记录？',`${x.name} 将从${action==='delete'?'库存':'购物清单'}移除。此操作不计为食用或丢弃。`,()=>update(s=>{const list=action==='delete'?s.items:s.shopping;const current=list.find(y=>y.id===id);if(!current||JSON.stringify(current)!==JSON.stringify(x))throw new Error('记录已更改，请关闭后重新确认。');if(action==='delete'){if(s.history.length>=10000)throw new Error('使用记录已满，请先备份并清空记录。');s.items=s.items.filter(y=>y.id!==id);s.history.unshift({id:uid(),kind:'delete',at:new Date().toISOString(),name:x.name,quantity:x.quantity,unit:x.unit});}else s.shopping=s.shopping.filter(y=>y.id!==id);return s;}));
});
$('#add').onclick=()=>edit(view==='shopping'?'shop':'add');for(const selector of ['#search','#filter','#location-filter','#inventory-order','#shopping-search'])$(selector).addEventListener('input',render);
$('#export').onclick=async()=>{try{state=await read();const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});if(blob.size>MAX_BACKUP_BYTES)throw new Error('备份超出可恢复的文件大小限制，请联系支持。');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`FreshLife-Web-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);const stamp=new Date().toLocaleString('zh-CN');$('#last-backup').textContent='上次发起导出：'+stamp+' · 请确认文件已下载';try{localStorage.setItem('freshlife-web-backup',stamp);}catch{}toast('备份已生成，请确认下载完成');}catch(err){toast('导出失败：'+message(err));}};
$('#import').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>MAX_BACKUP_BYTES)throw new Error('文件超过 20 MB，请选择网页版导出的备份。');let imported;try{imported=validateState(JSON.parse(await file.text()));}catch{throw new Error('文件无法识别。请选择 FreshLife 网页版导出的有效 JSON 备份，不支持 App 备份。');}const revision=(await read()).revision;ask('用备份替换当前数据？',`备份包含 ${imported.items.length} 件库存、${imported.shopping.length} 条购物清单、${imported.history.length} 条使用记录。将替换当前全部记录，无法撤销。建议先取消并导出当前备份。`,()=>update(s=>{return restoreBackup(s,imported,revision);}));}catch(err){toast(message(err));}};
$('#clear-history').onclick=()=>{const revision=state.revision;ask('清空使用记录？','库存和购物清单保留，使用记录无法撤销恢复。请先导出备份。',()=>update(s=>{if(s.revision!==revision)throw new Error('数据已变化，请关闭后重新确认。');s.history=[];return s;}));};
$('#clear-all').onclick=()=>{const revision=state.revision;ask('清空全部本地数据？','将删除此浏览器内的全部库存、购物清单和使用记录。没有云端副本，请先导出备份。',()=>update(s=>{if(s.revision!==revision)throw new Error('数据已变化，请关闭后重新确认。');return {...emptyState(),revision:s.revision};}));};
$('#theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').textContent=dark?'切换日间':'切换夜间';try{localStorage.setItem('freshlife-web-theme',dark?'dark':'light');}catch{}};
try{if(localStorage.getItem('freshlife-web-theme')==='dark')$('#theme').click();const stamp=localStorage.getItem('freshlife-web-backup');if(stamp)$('#last-backup').textContent='上次发起导出：'+stamp+' · 请确认文件已下载';}catch{}
$('#date-label').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
try{db=await openDB();state=await read();db.onversionchange=()=>{db.close();db=null;fatal('本地存储已更新，请刷新页面后继续。');};if('BroadcastChannel' in window){channel=new BroadcastChannel('freshlife-web');channel.onmessage=async()=>{try{state=await read();render();}catch(e){fatal(message(e));}};}}catch(err){fatal('本地数据未能读取。'+message(err)+' 未覆盖已有数据。');db?.close();db=null;}
setView(location.hash.slice(1));window.addEventListener('hashchange',()=>setView(location.hash.slice(1)));
document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&db){try{state=await read();render();}catch(e){fatal(message(e));}}});setInterval(render,60000);
if('serviceWorker' in navigator){navigator.serviceWorker.register('/app/sw.js',{scope:'/app/'}).then(()=>navigator.serviceWorker.ready).then(()=>$('#offline-status').textContent='离线缓存已就绪。这个浏览器再次打开时可离线使用。').catch(()=>$('#offline-status').textContent=navigator.serviceWorker.controller?'已通过离线缓存打开；连接网络后检查更新。':'离线缓存未就绪，重新打开页面时仍需要网络。');}else $('#offline-status').textContent='此浏览器不支持离线缓存，重新打开页面时需要网络。';

document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.target.closest('input,textarea,select,[contenteditable=true]')&&!document.querySelector('dialog[open]')){e.preventDefault();setView('pantry');$('#search').focus();}});

for(const id of ['#history-search','#history-kind'])$(id).addEventListener('input',()=>{historyLimit=100;render();});
$('#history-more').onclick=()=>{historyLimit+=100;render();};
$('#copy-shopping').onclick=async()=>{if(!state.shopping.length)return;const text=shoppingText(state.shopping);try{await navigator.clipboard.writeText(text);toast('清单已复制，可以粘贴到备忘录或聊天中');}catch{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`FreshLife-购物清单-${today()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('无法访问剪贴板，已改为下载清单文本');}};
